---
theme: jekyll-theme-minimal
title: N1ce1 Blog
description: Writeups for some online challenges

### Navigation menu

nav:
  - name: HTB-Hacknet
    link: /htb-hacknet/
  - name: About
    link: /about/
---
